.TL
OOPS Assignment 6
.AU
G.Akshay (25MCCE28)
.AI
University Of Hyderabad

.PP
1. Try out all the code demonstrated in the lectures.
.PDFPIC -C one.pdf 12c

.PP
2. We have discussed the following example as part of lecture on Abstract classes. Write a java
program to implement the respective classes. (2 points)
.PDFPIC -C q2.pdf 12c
.sp 0.5v

.sp 1
.PDFPIC -C two.pdf 12c
.sp 0.5v

.PP
3. Implement a class hierarchy, which has IMTechNumber at the top. Two classes derived
from the IMTechNumber: IMTechInteger and IMTechComplex classes. (8 points)
.PDFPIC -C three.pdf 12c
